name: Release

on:
  create:
    ref_type: tag
  release:
    types:
      - released

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: print Java version
      run: java -version
    - name: Build with Maven
      env:
        GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
        GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
      run: |
        mkdir -p ~/.gradle
        cat > ~/.gradle/gradle.properties <<!
        gradle.publish.key="${GRADLE_PUBLISH_KEY}"
        gradle.publish.secret="${GRADLE_PUBLISH_SECRET}"
        !
        ./gradlew build publishPlugins
